<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyBanLaptop" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=QuanLyBanLaptop;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False" SettingsObjectName="QuanLyBanLaptop_DAL.Properties.Settings" SettingsPropertyName="QuanLyBanLaptopConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AuditLogs" Member="AuditLogs">
    <Type Name="AuditLog">
      <Column Name="LogID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TableName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RecordID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="User_AuditLog" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Customer_DeviceUnit" Member="DeviceUnits" ThisKey="CustomerID" OtherKey="CurrentCustomerID" Type="DeviceUnit" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="CustomerID" OtherKey="CustomerID" Type="Order" />
      <Association Name="Customer_WarrantyClaim" Member="WarrantyClaims" ThisKey="CustomerID" OtherKey="CustomerID" Type="WarrantyClaim" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceUnits" Member="DeviceUnits">
    <Type Name="DeviceUnit">
      <Column Name="UnitID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SerialNumber" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PurchaseDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoldDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="WarrantyStartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="WarrantyEndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CurrentCustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DeviceUnit_OrderDetail" Member="OrderDetails" ThisKey="UnitID" OtherKey="UnitID" Type="OrderDetail" />
      <Association Name="DeviceUnit_WarrantyClaim" Member="WarrantyClaims" ThisKey="UnitID" OtherKey="UnitID" Type="WarrantyClaim" />
      <Association Name="Customer_DeviceUnit" Member="Customer" ThisKey="CurrentCustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="Product_DeviceUnit" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="OrderDetailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="DeviceUnit_OrderDetail" Member="DeviceUnit" ThisKey="UnitID" OtherKey="UnitID" Type="DeviceUnit" IsForeignKey="true" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
      <Association Name="Product_OrderDetail" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" ThisKey="OrderID" OtherKey="OrderID" Type="OrderDetail" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="User_Order" Member="User" ThisKey="CreatedBy" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SKU" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CPU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RAM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Storage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GPU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ScreenSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OS" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CostPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ReorderLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WarrantyMonths" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Product_DeviceUnit" Member="DeviceUnits" ThisKey="ProductID" OtherKey="ProductID" Type="DeviceUnit" />
      <Association Name="Product_OrderDetail" Member="OrderDetails" ThisKey="ProductID" OtherKey="ProductID" Type="OrderDetail" />
      <Association Name="Product_PurchaseDetail" Member="PurchaseDetails" ThisKey="ProductID" OtherKey="ProductID" Type="PurchaseDetail" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseDetails" Member="PurchaseDetails">
    <Type Name="PurchaseDetail">
      <Column Name="PurchaseDetailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PurchaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SerialFrom" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SerialTo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Product_PurchaseDetail" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
      <Association Name="PurchaseOrder_PurchaseDetail" Member="PurchaseOrder" ThisKey="PurchaseID" OtherKey="PurchaseID" Type="PurchaseOrder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseOrders" Member="PurchaseOrders">
    <Type Name="PurchaseOrder">
      <Column Name="PurchaseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="PurchaseOrder_PurchaseDetail" Member="PurchaseDetails" ThisKey="PurchaseID" OtherKey="PurchaseID" Type="PurchaseDetail" />
      <Association Name="Supplier_PurchaseOrder" Member="Supplier" ThisKey="SupplierID" OtherKey="SupplierID" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Supplier_PurchaseOrder" Member="PurchaseOrders" ThisKey="SupplierID" OtherKey="SupplierID" Type="PurchaseOrder" />
    </Type>
  </Table>
  <Table Name="dbo.WarrantyClaims" Member="WarrantyClaims">
    <Type Name="WarrantyClaim">
      <Column Name="ClaimID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UnitID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IssueDescription" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Resolution" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="Customer_WarrantyClaim" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="DeviceUnit_WarrantyClaim" Member="DeviceUnit" ThisKey="UnitID" OtherKey="UnitID" Type="DeviceUnit" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AvatarPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="User_AuditLog" Member="AuditLogs" ThisKey="UserID" OtherKey="UserID" Type="AuditLog" />
      <Association Name="User_Order" Member="Orders" ThisKey="UserID" OtherKey="CreatedBy" Type="Order" />
    </Type>
  </Table>
</Database>